name: exercise_e8
description: Exercise E8

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 4.0.2
  firebase_core: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
