// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT26ANiFgJpywEiH94lOT0RKmM3FIsTwA',
    appId: '1:970341220498:web:8b0bffcb2fc90323c2a64b',
    messagingSenderId: '970341220498',
    projectId: 'mobile-e8',
    authDomain: 'mobile-e8.firebaseapp.com',
    storageBucket: 'mobile-e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQIt_COH2m-DKf5ke6tciCUsgJiMmxf9M',
    appId: '1:970341220498:android:69be8b3dd2bde7c8c2a64b',
    messagingSenderId: '970341220498',
    projectId: 'mobile-e8',
    storageBucket: 'mobile-e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnjvwLd4cluSbQzJGtsfi-Okwn7xzd7W0',
    appId: '1:970341220498:ios:d0f6148f88f09507c2a64b',
    messagingSenderId: '970341220498',
    projectId: 'mobile-e8',
    storageBucket: 'mobile-e8.appspot.com',
    iosClientId: '970341220498-ane8vfavfmifda5i97b0378os7e8amjn.apps.googleusercontent.com',
    iosBundleId: 'no.ntnu.exerciseE8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnjvwLd4cluSbQzJGtsfi-Okwn7xzd7W0',
    appId: '1:970341220498:ios:d0f6148f88f09507c2a64b',
    messagingSenderId: '970341220498',
    projectId: 'mobile-e8',
    storageBucket: 'mobile-e8.appspot.com',
    iosClientId: '970341220498-ane8vfavfmifda5i97b0378os7e8amjn.apps.googleusercontent.com',
    iosBundleId: 'no.ntnu.exerciseE8',
  );
}
